import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { BrowserRouter, Link, Navigate, Route, Routes } from 'react-router-dom';
import { TopBar } from '../components/ui/TopBar';
import { LoginPage } from '../features/auth/LoginPage';
import { QuickAttendancePage } from '../features/attendance/QuickAttendancePage';
import { DashboardPage } from '../features/dashboard/DashboardPage';
import { ImportsPage, PlaceholderPage, ReportsPage } from '../pages/SimplePages';
import { SelectClassPage, SelectLessonPage, SelectSchoolPage } from '../pages/SelectionPages';
const qc=new QueryClient();
function Shell(){return <><TopBar/><nav className="mx-auto flex max-w-7xl gap-2 overflow-x-auto px-4 py-3 text-sm font-bold"><Link className="nav" to="/dashboard">Dashboard</Link><Link className="nav" to="/escolas">Nova chamada</Link><Link className="nav" to="/calendarios">Calendários</Link><Link className="nav" to="/planejamento-semanal">Planejamento semanal</Link><Link className="nav" to="/historico">Histórico</Link><Link className="nav" to="/alunos">Alunos</Link><Link className="nav" to="/importacao">Importação</Link><Link className="nav" to="/relatorios">Relatórios</Link><Link className="nav" to="/alertas">Alertas</Link><Link className="nav" to="/configuracoes">Configurações</Link></nav><Routes><Route path="/dashboard" element={<DashboardPage/>}/><Route path="/escolas" element={<SelectSchoolPage/>}/><Route path="/turmas" element={<SelectClassPage/>}/><Route path="/aulas" element={<SelectLessonPage/>}/><Route path="/chamada" element={<QuickAttendancePage/>}/><Route path="/calendarios" element={<PlaceholderPage type="calendars"/>}/><Route path="/planejamento-semanal" element={<PlaceholderPage type="weeklyPlanning"/>}/><Route path="/historico" element={<PlaceholderPage type="history"/>}/><Route path="/alunos" element={<PlaceholderPage type="students"/>}/><Route path="/importacao" element={<ImportsPage/>}/><Route path="/relatorios" element={<ReportsPage/>}/><Route path="/estatisticas-aluno" element={<PlaceholderPage type="studentStats"/>}/><Route path="/estatisticas-turma" element={<PlaceholderPage type="classStats"/>}/><Route path="/alertas" element={<PlaceholderPage type="alerts"/>}/><Route path="/configuracoes" element={<PlaceholderPage type="settings"/>}/><Route path="*" element={<Navigate to="/dashboard"/>}/></Routes></>}
export default function App(){return <QueryClientProvider client={qc}><BrowserRouter><Routes><Route path="/login" element={<LoginPage/>}/><Route path="/*" element={<Shell/>}/></Routes></BrowserRouter></QueryClientProvider>}
