import puppeteer from 'puppeteer-core';
import fs from 'node:fs';
const session = JSON.parse(fs.readFileSync('/tmp/session.json','utf8'));
const b = await puppeteer.launch({executablePath:'/usr/bin/google-chrome-stable',headless:'new',args:['--no-sandbox']});
const p = await b.newPage(); await p.setViewport({width:1280,height:900});
const errs=[]; p.on('pageerror',e=>errs.push(e.message));
await p.goto('http://localhost:5173/',{waitUntil:'domcontentloaded'});
await p.evaluate(([k,v])=>localStorage.setItem(k,v),['sb-rogvgrnkjvxdulkcunuo-auth-token',JSON.stringify(session)]);
await p.goto('http://localhost:5173/escolas',{waitUntil:'networkidle2'});
await new Promise(x=>setTimeout(x,1500));
console.log('h1:', await p.evaluate(()=>document.querySelector('main h1,div h1')?.textContent));
const btns = await p.evaluate(()=>[...document.querySelectorAll('button')].map(b=>b.textContent.trim()).filter(Boolean).slice(0,8));
console.log('botoes topo:', JSON.stringify(btns));
await p.evaluate(()=>{const b=[...document.querySelectorAll('button')].find(x=>x.textContent.includes('Importar')); if(b)b.click();});
await new Promise(x=>setTimeout(x,800));
console.log('modal title:', await p.evaluate(()=>document.querySelector('[id^=headlessui-dialog-title]')?.textContent||'NENHUM'));
console.log('tem "Baixar planilha modelo":', await p.evaluate(()=>[...document.querySelectorAll('*')].some(e=>e.childNodes.length&&/Baixar planilha modelo/.test(e.textContent))));
console.log('select dentro do modal:', await p.evaluate(()=>!!document.querySelector('[role=dialog] select, [id^=headlessui-dialog] select')));
console.log('erros:', errs.length?errs.join(' | '):'NENHUM');
await b.close();
